### ISSUE TITLE
Provide PowerShell 7.0 support

### ISSUE THREAD

**Issue by JamieB226-westrock** [sorengranfeldt/psma#14]
The current version of the PSMA calls the latest version of Windows PowerShell.  There is no option to specify an alternate PowerShell environment (pwsh.exe).  I verified that with PowerShell 7.0 installed the MA continues to call the currently installed version of Windows PowerShell.

**Comment by sorengranfeldt** [comment]
I'll have to look further into this. It may be a bigger change since there need to support .NET Core and the .NET System.Automation has to support PS 7. Will have a look when time allows.

If you can provide links or samples on how to instantiate PS V7 hosts from C#, I'll be very happy to receive those.

**Comment by JamieB226-westrock** [comment]
Something simple like the below works if you reference the assemblies from the C:\program files\PowerShell\7 folder.  I'm guessing that's not what you need.  You need a way to detect or let the user specify the assembly.  That is way above my C# level.  Sorry.

using System;
using System.Management.Automation;
using System.Collections.ObjectModel;

namespace PowerShellExecutionSample
{
    class Program
    {
        static void Main(string[] args)
        {
            using (PowerShell PowerShellInstance = PowerShell.Create())
            {
                PowerShellInstance.AddScript("$PSVersionTable.PSVersion.ToString()");
                Collection<PSObject> PSOutput = PowerShellInstance.Invoke();
                foreach (PSObject outputItem in PSOutput)
                {
                    // if null object was dumped to the pipeline during the script then a null
                    // object may be present here. check for null to prevent potential NRE.
                    if (outputItem != null)
                    {
                        Console.WriteLine(outputItem);
                    }
                }
            }
        }
    }
}

**Comment by lehtoj** [comment]
I second this. Support for PowerShell versions higher than 5.1 would be very nice, due to the massive amount of improvements (bug fixes, new features and better performance) newer versions have received.

It may be necessary to have the user provide location of the pwsh.exe, since it could really be anywhere.

I just recently tried to write my own ECMA 2.2 management agent in C#, but I gave up due to the complexity of implementing everything from scratch, including impersonation.

My biggest gripe with PSMA is how finicky it is with string conversions. Popular error in my event log is
` "System.InvalidCastException: Unable to cast object of type 'System.Management.Automation.PSObject' to type 'System.String'.`

Hunting down these errors probably takes more time than anything else in making PSMA's. But I recently discovered I can use PowerShell 5 classes in PSMA projects. It has reduced type errors considerably.

**Comment by sorengranfeldt** [comment]
I see that I may have to look into creating a version of the PSMA that supports PS7. It may be that I have to create separate releases and see where that takes it.

It seems like there is still a lot of people out there using it.

**Comment by sorengranfeldt** [comment]
> I second this. Support for PowerShell versions higher than 5.1 would be very nice, due to the massive amount of improvements (bug fixes, new features and better performance) newer versions have received.
> 
> It may be necessary to have the user provide location of the pwsh.exe, since it could really be anywhere.
> 
> I just recently tried to write my own ECMA 2.2 management agent in C#, but I gave up due to the complexity of implementing everything from scratch, including impersonation. As such, it'd be nice being able to use latest PS versions in PSMA.
> 
> My biggest gripe with PSMA is how finicky it is with string conversions. Popular error in my event log is
> ` "System.InvalidCastException: Unable to cast object of type 'System.Management.Automation.PSObject' to type 'System.String'.`
> 
> Hunting down these errors probably takes more time than anything else in making PSMA's. But I recently discovered I can use PowerShell 5 classes in PSMA projects. It has reduced type errors considerably. New PS versions have even improved support for classes.

---
Are the errors you describe above, in this PSMA ? Have you tried using the Debug options that it offers for outputting in your scripts? Just curios to know how I can make it better for these types of situations and debugging scenarios.

Thanks.

**Comment by sorengranfeldt** [comment]
Will still have a look at this

**Comment by sorengranfeldt** [comment]
There is a version coming soon that support PS7+
